**Environment Set-Up**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np

**Data Loading (BRCA, COAD, KIRC, LUAD)**

In [3]:
brca = pd.read_csv('/content/drive/My Drive/Colab Notebooks/BINF 3350: Genomics & Bioinformatics/brca_sig.csv', sep=',')
brca = brca[["cancer_type", "ncbi_gene_id", "gene_symbol", "fdr_adjusted_p_value", "log2_fold_change"]]
brca

,cancer_type,ncbi_gene_id,gene_symbol,fdr_adjusted_p_value,log2_fold_change
0,BRCA,9636,ISG15,1.000000e-20,2.392468
1,BRCA,8784,TNFRSF18,1.000000e-20,2.275401
2,BRCA,441869,ANKRD65,1.000000e-20,-1.642720
3,BRCA,2563,GABRD,1.000000e-20,2.082703
4,BRCA,9651,PLCH2,2.770700e-19,-2.263603
...,...,...,...,...,...
1376,BRCA,57595,PDZD4,5.677900e-14,-1.963182
1377,BRCA,554,AVPR2,1.000000e-20,-3.378095
1378,BRCA,8270,LAGE3,1.000000e-20,1.586527
1379,BRCA,2157,F8,1.000000e-20,-1.803112
1380,BRCA,1193,CLIC2,1.000000e-20,-1.561048

In [4]:
coad = pd.read_csv('/content/drive/My Drive/Colab Notebooks/BINF 3350: Genomics & Bioinformatics/coad_sig.csv', sep=',')
coad = coad[["cancer_type", "ncbi_gene_id", "gene_symbol", "fdr_adjusted_p_value", "log2_fold_change"]]
coad

,cancer_type,ncbi_gene_id,gene_symbol,fdr_adjusted_p_value,log2_fold_change
0,COAD,84069,PLEKHN1,1.000000e-20,1.593593
1,COAD,1953,MEGF6,1.000000e-20,1.755102
2,COAD,106614088,MIR34AHG,8.475300e-19,1.554834
3,COAD,10630,PDPN,1.000000e-20,1.753934
4,COAD,284723,SLC25A34,1.784500e-14,-3.617534
...,...,...,...,...,...
939,COAD,10813,UTP14A,1.000000e-20,1.520153
940,COAD,90161,HS6ST2,1.000000e-20,3.067983
941,COAD,2564,GABRE,1.000000e-20,2.128198
942,COAD,633,BGN,1.000000e-20,2.698140
943,COAD,1736,DKC1,1.000000e-20,1.585123

In [5]:
kirc = pd.read_csv('/content/drive/My Drive/Colab Notebooks/BINF 3350: Genomics & Bioinformatics/kirc_sig.csv', sep=',')
kirc = kirc[["cancer_type", "ncbi_gene_id", "gene_symbol", "fdr_adjusted_p_value", "log2_fold_change"]]
kirc

,cancer_type,ncbi_gene_id,gene_symbol,fdr_adjusted_p_value,log2_fold_change
0,KIRC,102466751,MIR6859-1,1.000000e-20,1.981901
1,KIRC,57801,HES4,1.000000e-20,2.096344
2,KIRC,8784,TNFRSF18,1.000000e-20,1.569977
3,KIRC,7293,TNFRSF4,1.000000e-20,2.997710
4,KIRC,2563,GABRD,1.000000e-20,4.275529
...,...,...,...,...,...
1701,KIRC,139728,PNCK,1.000000e-20,6.500308
1702,KIRC,3897,L1CAM,3.391000e-18,-6.080103
1703,KIRC,554,AVPR2,1.280900e-12,-4.031331
1704,KIRC,139716,GAB3,1.000000e-20,1.554767
1705,KIRC,4515,MTCP1,1.000000e-20,1.876566

In [6]:
luad = pd.read_csv('/content/drive/My Drive/Colab Notebooks/BINF 3350: Genomics & Bioinformatics/luad_sig.csv', sep=',')
luad = luad[["cancer_type", "ncbi_gene_id", "gene_symbol", "fdr_adjusted_p_value", "log2_fold_change"]]
luad

,cancer_type,ncbi_gene_id,gene_symbol,fdr_adjusted_p_value,log2_fold_change
0,LUAD,84069,PLEKHN1,1.000000e-20,2.422771
1,LUAD,8784,TNFRSF18,1.000000e-20,2.086583
2,LUAD,339456,TMEM52,1.000000e-20,1.574812
3,LUAD,27237,ARHGEF16,1.000000e-20,1.712965
4,LUAD,388591,RNF207,1.000000e-20,1.551146
...,...,...,...,...,...
1256,LUAD,3149,HMGB3,1.000000e-20,3.156008
1257,LUAD,5365,PLXNB3,1.000000e-20,2.434562
1258,LUAD,26576,SRPK3,1.000000e-20,2.203514
1259,LUAD,554,AVPR2,2.804300e-13,-1.791606
1260,LUAD,2157,F8,1.622800e-11,-1.795806

**Identify Shared DEGs Across Cancer Types**

In [7]:
shared = pd.merge(pd.merge(pd.merge(brca, coad, on = ['ncbi_gene_id', 'gene_symbol']), kirc, on = ['ncbi_gene_id', 'gene_symbol']), luad, on = ['ncbi_gene_id', 'gene_symbol'])
shared.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'cancer_type_x', 'fdr_adjusted_p_value_x', 'log2_fold_change_x'} in the result is deprecated and will raise a MergeError in a future version.
  """Entry point for launching an IPython kernel.

,cancer_type_x,ncbi_gene_id,gene_symbol,fdr_adjusted_p_value_x,log2_fold_change_x,cancer_type_y,fdr_adjusted_p_value_y,log2_fold_change_y,cancer_type_x,fdr_adjusted_p_value_x,log2_fold_change_x,cancer_type_y,fdr_adjusted_p_value_y,log2_fold_change_y
0,BRCA,128239,IQGAP3,1.000000e-20,3.725825,COAD,1.000000e-20,2.070796,KIRC,1.000000e-20,1.663117,LUAD,1.000000e-20,3.521805
1,BRCA,6241,RRM2,1.000000e-20,3.391862,COAD,1.000000e-20,1.696422,KIRC,4.795600e-15,2.333840,LUAD,1.000000e-20,3.249844
2,BRCA,699,BUB1,1.000000e-20,3.288360,COAD,1.000000e-20,1.637324,KIRC,5.529100e-12,1.753177,LUAD,1.000000e-20,2.573548
3,BRCA,1290,COL5A2,1.000000e-20,1.723367,COAD,1.000000e-20,1.845367,KIRC,1.000000e-20,1.985023,LUAD,1.000000e-20,1.861748
4,BRCA,11170,FAM107A,1.000000e-20,-4.267759,COAD,4.068200e-11,-3.863410,KIRC,1.000000e-20,-1.817739,LUAD,7.563100e-13,-4.803873

In [8]:
list(shared.columns)

['cancer_type_x',
 'ncbi_gene_id',
 'gene_symbol',
 'fdr_adjusted_p_value_x',
 'log2_fold_change_x',
 'cancer_type_y',
 'fdr_adjusted_p_value_y',
 'log2_fold_change_y',
 'cancer_type_x',
 'fdr_adjusted_p_value_x',
 'log2_fold_change_x',
 'cancer_type_y',
 'fdr_adjusted_p_value_y',
 'log2_fold_change_y']

**Identify Shared DEGs Across Cancer Types**

In [9]:
sharedDF = shared.set_axis(['BRCA', 'NCBI_Gene_ID', 'Gene_Symbol', 'BRCA_FDR', 'BRCA_LFC', 'COAD', 'COAD_FDR', 'COAD_LFC', 'KIRC', 'KIRC_FDR', 'KIRC_LFC', 'LUAD', 'LUAD_FDR', 'LUAD_LFC'], axis = 1, inplace = False)
subsetDF = sharedDF[['NCBI_Gene_ID', 'Gene_Symbol', 'BRCA_FDR', 'BRCA_LFC', 'COAD_FDR', 'COAD_LFC', 'KIRC_FDR', 'KIRC_LFC', 'LUAD_FDR', 'LUAD_LFC']]
subsetDF.index = np.arange(1, len(subsetDF) + 1)
subsetDF

,NCBI_Gene_ID,Gene_Symbol,BRCA_FDR,BRCA_LFC,COAD_FDR,COAD_LFC,KIRC_FDR,KIRC_LFC,LUAD_FDR,LUAD_LFC
1,128239,IQGAP3,1.000000e-20,3.725825,1.000000e-20,2.070796,1.000000e-20,1.663117,1.000000e-20,3.521805
2,6241,RRM2,1.000000e-20,3.391862,1.000000e-20,1.696422,4.795600e-15,2.333840,1.000000e-20,3.249844
3,699,BUB1,1.000000e-20,3.288360,1.000000e-20,1.637324,5.529100e-12,1.753177,1.000000e-20,2.573548
4,1290,COL5A2,1.000000e-20,1.723367,1.000000e-20,1.845367,1.000000e-20,1.985023,1.000000e-20,1.861748
5,11170,FAM107A,1.000000e-20,-4.267759,4.068200e-11,-3.863410,1.000000e-20,-1.817739,7.563100e-13,-4.803873
6,125,ADH1B,9.686700e-13,-6.394212,1.088800e-12,-6.026070,1.453500e-12,-4.336386,1.000000e-20,-4.337517
7,9319,TRIP13,1.000000e-20,2.111323,1.000000e-20,2.421709,1.000000e-20,1.584231,1.000000e-20,2.902119
8,57556,SEMA6A,1.000000e-20,-2.058443,4.640300e-19,-2.736862,1.000000e-20,1.776406,5.045800e-15,-2.864175
9,10112,KIF20A,1.000000e-20,3.665427,1.000000e-20,1.658623,6.559800e-20,2.134878,1.000000e-20,3.311439
10,25928,SOSTDC1,1.299700e-13,-4.252037,4.275300e-13,-1.804630,2.718100e-20,-5.650733,3.085300e-13,-5.239818
11,54443,ANLN,1.000000e-20,3.238603,1.000000e-20,2.404003,2.619200e-11,2.244583,1.000000e-20,3.572064
12,948,CD36,1.493000e-17,-5.051062,4.983900e-11,-3.139905,1.000000e-20,2.263184,1.000000e-20,-3.728134
13,27299,ADAMDEC1,1.000000e-20,2.297191,2.219200e-14,-3.964322,1.512100e-19,1.572890,1.000000e-20,2.320916
14,115908,CTHRC1,1.000000e-20,2.390296,1.000000e-20,3.544902,1.116200e-17,2.780836,1.000000e-20,4.360558
15,9833,MELK,1.000000e-20,3.298098,1.000000e-20,1.540580,5.194400e-15,1.810649,1.000000e-20,3.571608
16,1289,COL5A1,1.000000e-20,1.871325,1.000000e-20,1.581175,4.865000e-17,1.903682,1.000000e-20,1.768086
17,55165,CEP55,1.000000e-20,3.302970,1.000000e-20,1.924445,3.993500e-18,2.069358,1.000000e-20,3.296960
18,6330,SCN4B,1.000000e-20,-3.170711,6.807600e-16,-2.252173,1.000000e-20,1.552153,5.683000e-16,-3.044273
19,57447,NDRG2,1.000000e-20,-2.775634,1.000000e-20,-1.542652,1.000000e-20,-1.517315,1.000000e-20,-1.795995
20,80031,SEMA6D,1.000000e-20,-2.510962,1.855300e-15,-3.335850,7.470500e-17,-3.422810,3.248900e-15,-2.869694
21,84951,TNS4,2.932900e-18,-2.590834,1.000000e-20,3.354482,2.541300e-11,-1.789521,1.000000e-20,2.264083
22,1277,COL1A1,1.000000e-20,2.429837,1.000000e-20,2.504689,2.906200e-15,2.936054,1.000000e-20,2.966282
23,762,CA4,1.000000e-20,-4.524565,1.453900e-13,-9.112958,1.664600e-15,-2.881960,5.798200e-18,-5.608543
24,10351,ABCA8,1.000000e-20,-4.647862,1.688700e-18,-4.066089,1.375400e-11,-2.765256,1.000000e-20,-3.556505
25,332,BIRC5,1.000000e-20,3.742228,1.000000e-20,1.544629,1.000000e-20,2.557533,1.000000e-20,3.727510
26,80164,PRR36,1.000000e-20,1.743232,1.000000e-20,2.082021,8.616200e-14,-1.929033,1.000000e-20,1.900337
27,22974,TPX2,1.000000e-20,3.532808,1.000000e-20,1.944340,1.292100e-17,2.481816,1.000000e-20,3.515342
28,4605,MYBL2,1.000000e-20,3.604545,1.000000e-20,1.870785,8.074800e-12,2.054848,1.000000e-20,4.254238
29,11065,UBE2C,1.000000e-20,4.066457,1.000000e-20,1.950558,3.096400e-18,2.786924,1.000000e-20,4.039435
30,8318,CDC45,1.000000e-20,2.766584,1.000000e-20,1.677317,2.784800e-11,1.595504,1.000000e-20,3.155661
31,4320,MMP11,1.000000e-20,5.982079,1.000000e-20,3.607467,1.000000e-20,2.245967,3.843100e-18,5.038402

**Export Shared DEGs**

In [10]:
subsetDF.to_csv('/content/drive/My Drive/Colab Notebooks/BINF 3350: Genomics & Bioinformatics/sharedDEGs.csv', index = False)